# Generated by Django 4.0.3 on 2022-03-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
    ]
