# Generated by Django 4.0.3 on 2022-03-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20220318_0245'),
    ]

    operations = [
    ]
